#tenants:
#    tenant_id:
#        - <tenant_id>
#instances:
#    id:
#        - <server_id1>
#        - <server_id2>
#images:
#    images_list:
#        - <image_id1>
#        - <image_id2>
#    exclude_public_and_members: True
#volumes:
#    volumes_list:
#        - <volume_id1>
#        - <volume_id2>
#    date: "%Y-%m-%d %H:%M:%S"
