version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(bg_black)s%(log_color)s%(levelname)-8s %(current_task)s%(reset)s %(bg_cyan)s %(asctime)s %(reset)s %(bg_black)s%(log_color)s%(message)s%(reset)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: white
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
  console_colored:
    (): colorlog.ColoredFormatter
    format: '%(bg_black)s%(log_color)s%(levelname)-8s %(current_task)s%(reset)s %(bg_blue)s[%(pathname)s : lineno %(lineno)s]%(reset)s %(bg_cyan)s %(asctime)s %(reset)s %(bg_black)s%(log_color)s%(message)s%(reset)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: white
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
filters:
  show_current_task:
    (): cloudferrylib.utils.log.CurrentTaskFilter
    name_format: '%(name)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_colored
    stream: ext://sys.stdout
    filters: [show_current_task]
  info:
    backupCount: 20
    class: cloudferrylib.utils.log.RunRotatingFileHandler
    encoding: utf-8
    filename: 'info-%(scenario)s-%(date)s.log'
    date_format: '%F-%H-%M-%S'
    formatter: colored
    level: INFO
    maxBytes: 10485760
    filters: [show_current_task]
  error:
    backupCount: 20
    class: cloudferrylib.utils.log.RunRotatingFileHandler
    encoding: utf-8
    filename: 'error-%(scenario)s-%(date)s.log'
    date_format: '%F-%H-%M-%S'
    formatter: colored
    level: ERROR
    maxBytes: 10485760
    filters: [show_current_task]
loggers:
  paramiko.transport:
    level: WARNING
    handlers: [console, info, error]
  glanceclient.common.http:
    level: WARNING
    handlers: [console, info, error]
  requests.packages.urllib3.connectionpool:
    level: WARNING
    handlers: [console, info, error]

root:
  level: INFO
  handlers: [console, info, error]
